### ISSUE TITLE
plugin dir error

### ISSUE THREAD

**Issue by adnankhairy** [mysqludf/lib_mysqludf_str#1]
when i tried to exc 
SHOW VARIABLES LIKE 'plugin_dir';

it's return null 

i tried to verify plugin dir by putting this in my.ini
plugin_dir=c:/wamp/bin/mysql/mysql5.0.51b/plugin

but mysql service in windows wamp servier is down 

any help!

**Comment by jasny** [comment]
[See the docs](http://dev.mysql.com/doc/refman/5.0/en/udf-compiling.html)

> Prior to MySQL 5.0.67, or if the value of plugin_dir is empty, the shared object should be placed in a directory such as /usr/lib that is searched by your system's dynamic (runtime) linker, or you can add the directory in which you place the shared object to the linker configuration file (for example, /etc/ld.so.conf).

**Comment by adnankhairy** [comment]
sorry but i don't understand iam using windows 7 - 64 bit , WampServer Version 2.0
mysql 5.0.51b -- php 5.2.6 -- apache 2.2.8
can you please be more specific

**Comment by jasny** [comment]
Read the docs or ask the question at http://serverfault.com/. Locating the plugin dir of an old MySQL install can't be reported as issue of this library.

**Comment by adnankhairy** [comment]
instead of your 2 comments not helped me, you can simply said that
"you need to upgrade your mysql version"
